# Generated by Django 4.2 on 2023-05-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0002_spirit_scolaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scolaire',
            old_name='filiere',
            new_name='filieres',
        ),
        migrations.AlterField(
            model_name='spirit',
            name='baptism_spirit',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='baptism_water',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=None, max_length=3),
        ),
        migrations.CreateModel(
            name='professionnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=80)),
                ('working', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3)),
                ('description', models.TextField(default=None, null=True)),
                ('cv', models.FileField(upload_to='PDF/CV/')),
                ('image_de_profil', models.ImageField(upload_to='Pictures/profil')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaires.person')),
            ],
        ),
    ]
