# Generated by Django 4.2 on 2023-05-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0003_rename_filiere_scolaire_filieres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nom',
            new_name='name',
        ),
    ]
