# Generated by Django 4.2 on 2023-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0004_rename_nom_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='commune',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='numero',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='prenoms',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
