# Generated by Django 4.2 on 2023-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0005_alter_person_commune_alter_person_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolaire',
            name='person',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='commune',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='prenoms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='professionnal',
        ),
        migrations.DeleteModel(
            name='scolaire',
        ),
        migrations.DeleteModel(
            name='spirit',
        ),
    ]
