# Generated by Django 4.2 on 2023-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0006_remove_scolaire_person_remove_spirit_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prenoms',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
