# Generated by Django 4.2 on 2023-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0007_alter_person_prenoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='numero',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
