# Generated by Django 4.2 on 2023-05-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0009_alter_person_date_alter_person_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
