# Generated by Django 3.1.14 on 2023-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0012_alter_person_prenoms_spirit_scolaire_professionnal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionnal',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='professionnal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='professionnal',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='professionnal',
            name='image_de_profil',
        ),
        migrations.RemoveField(
            model_name='professionnal',
            name='person',
        ),
        migrations.RemoveField(
            model_name='professionnal',
            name='working',
        ),
        migrations.RemoveField(
            model_name='scolaire',
            name='diplomes',
        ),
        migrations.RemoveField(
            model_name='scolaire',
            name='filieres',
        ),
        migrations.RemoveField(
            model_name='scolaire',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='scolaire',
            name='person',
        ),
        migrations.RemoveField(
            model_name='scolaire',
            name='series',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='baptism_spirit',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='baptism_water',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='community',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='jeunesse',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionnal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
