# Generated by Django 3.1.14 on 2023-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0013_auto_20230522_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
