# Generated by Django 3.1.14 on 2023-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0015_spirit_baptism_spirit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='baptism_water',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=None, max_length=3),
        ),
    ]
