# Generated by Django 3.1.14 on 2023-05-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0016_spirit_baptism_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='community',
            field=models.CharField(choices=[('ORDRE ET ACCEUIL', 'ORDRE ET ACCEUIL'), ('COMMITE SOCIAL', 'COMMITE SOCIAL')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='spirit',
            name='jeunesse',
            field=models.CharField(choices=[('ESTER', 'ESTHER'), ('EMMANUEL', 'EMMANUEL'), ('JOSUE', 'JOSUE'), ('OSE', 'OSE')], default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='spirit',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.person'),
        ),
    ]
