# Generated by Django 3.1.14 on 2023-05-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0017_auto_20230522_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='scolaire',
            name='diplomes',
            field=models.CharField(choices=[('CEPE', 'CEPE'), ('BEPEC', 'BEPEC'), ('BACCALAUREAT', 'BACCALAUREAT'), ('BTS', 'BTS'), ('LICENCE 3', 'LICENCE 3'), ('MASTER', 'MASTER'), ('DOCTORAT', 'DOCTORAT'), ('DUT', 'DUT')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='scolaire',
            name='esprit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.spirit'),
        ),
        migrations.AddField(
            model_name='scolaire',
            name='filieres',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='scolaire',
            name='niveau',
            field=models.CharField(choices=[('JE CONTINUE LES COURS', 'JE CONTINUE LES COURS'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('SIXIEME', 'SIXIEME'), ('CINQUIEME', 'CINQUIEME'), ('QUATRIEME', 'QUATRIEME'), ('TROISIEME', 'TROISIEME'), ('SECOND', 'SECOND'), ('PREMIERE', 'PREMIERE'), ('TERMINAL', 'TERMINAL'), ('LICENCE 1', 'LICENCE 1'), ('LICENCE 2', 'LICENCE 2'), ('LICENCE 3', 'LICENCE 3'), ('MASTER 1', 'MASTER 1'), ('MASTER 2', 'MASTER 2'), ('DOCTORAT', 'DOCTORAT')], max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='scolaire',
            name='series',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=12, null=True),
        ),
    ]
