# Generated by Django 3.1.14 on 2023-05-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0018_auto_20230522_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnal',
            name='cv',
            field=models.FileField(null=True, upload_to='PDF/CV/'),
        ),
        migrations.AddField(
            model_name='professionnal',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='professionnal',
            name='domaine',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='professionnal',
            name='image_de_profil',
            field=models.ImageField(null=True, upload_to='Pictures/profil'),
        ),
        migrations.AddField(
            model_name='professionnal',
            name='scol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.scolaire'),
        ),
        migrations.AddField(
            model_name='professionnal',
            name='working',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
    ]
