# Generated by Django 3.1.14 on 2023-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0021_auto_20230522_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='numero',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
