# Generated by Django 3.1.14 on 2023-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0022_auto_20230616_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnal',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='professionnal',
            name='domaine',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('telecommunications', 'Télécommunications'), ('petrole_gaz', 'Pétrole et gaz'), ('banque_finance', 'Banque et finance'), ('energie', 'Énergie'), ('tourisme', 'Tourisme'), ('commerce', 'Commerce'), ('construction_immobilier', 'Construction et immobilier'), ('manufacturier', 'Manufacturier'), ('services', 'Services'), ('transport_logistique', 'Transport et logistique'), ('technologie', "Technologie de l'information"), ('education', 'Éducation'), ('sante', 'Santé'), ('media', 'Média et communication'), ('mode', 'Mode et textile'), ('art_culture', 'Art et culture'), ('sport', 'Sport et loisirs'), ('restauration', 'Restauration'), ('automobile', 'Automobile'), ('environnement', 'Environnement')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='professionnal',
            name='metier',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='professionnal',
            name='working',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='filieres',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='niveau',
            field=models.CharField(blank=True, choices=[('JE CONTINUE LES COURS', 'JE CONTINUE LES COURS'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('SIXIEME', 'SIXIEME'), ('CINQUIEME', 'CINQUIEME'), ('QUATRIEME', 'QUATRIEME'), ('TROISIEME', 'TROISIEME'), ('SECOND', 'SECOND'), ('PREMIERE', 'PREMIERE'), ('TERMINAL', 'TERMINAL'), ('LICENCE 1', 'LICENCE 1'), ('LICENCE 2', 'LICENCE 2'), ('LICENCE 3', 'LICENCE 3'), ('MASTER 1', 'MASTER 1'), ('MASTER 2', 'MASTER 2'), ('DOCTORAT', 'DOCTORAT')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='scolaire',
            name='series',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='community',
            field=models.CharField(blank=True, choices=[('ORDRE ET ACCEUIL', 'ORDRE ET ACCEUIL'), ('COMMITE SOCIAL', 'COMMITE SOCIAL')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='jeunesse',
            field=models.CharField(blank=True, choices=[('ESTER', 'ESTHER'), ('EMMANUEL', 'EMMANUEL'), ('JOSUE', 'JOSUE'), ('OSE', 'OSE')], default=None, max_length=8, null=True),
        ),
    ]
